# Generated by Django 6.0.5 on 2026-05-25 09:52

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiaire',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prenom', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('nationalite', models.CharField(default='Non spécifiée', max_length=100)),
                ('pays_residence', models.CharField(max_length=100)),
                ('situation_familiale', models.CharField(blank=True, max_length=100)),
                ('revenus_mensuels', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bénéficiaire',
                'verbose_name_plural': 'Bénéficiaires',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(editable=False, max_length=20, unique=True)),
                ('type_aide', models.CharField(choices=[('financiere', '💰 Aide financière'), ('alimentaire', '🍽️ Aide alimentaire'), ('medicale', '🏥 Assistance médicale'), ('logement', '🏠 Aide au logement'), ('accompagnement', '🧠 Accompagnement')], max_length=20)),
                ('montant_demande', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('motif', models.TextField()),
                ('urgence', models.CharField(choices=[('faible', '🟢 Faible'), ('normal', '🟠 Normal'), ('urgent', '🔴 Urgent')], default='normal', max_length=10)),
                ('statut', models.CharField(choices=[('soumise', '📝 Soumise'), ('en_cours', '⏳ En cours'), ('approuvee', '✅ Approuvée'), ('rejetee', '❌ Rejetée')], default='soumise', max_length=15)),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('notes_internes', models.TextField(blank=True)),
                ('agent_assigne', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_assignees', to=settings.AUTH_USER_MODEL)),
                ('beneficiaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to='api.beneficiaire')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_possedees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Demande',
                'verbose_name_plural': 'Demandes',
                'ordering': ['-date_soumission'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_document', models.CharField(max_length=100)),
                ('fichier', models.FileField(upload_to='documents/%Y/%m/')),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('verifie', models.BooleanField(default=False)),
                ('commentaire', models.TextField(blank=True)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='api.demande')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-date_upload'],
            },
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_intervention', models.CharField(choices=[('financiere', '💰 Aide financière'), ('alimentaire', '🍽️ Aide alimentaire'), ('medicale', '🏥 Assistance médicale'), ('logement', '🏠 Aide au logement'), ('accompagnement', '🧠 Accompagnement')], max_length=20)),
                ('montant_accorde', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('date_realisation', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('document_justificatif', models.FileField(blank=True, null=True, upload_to='interventions/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('demande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='intervention', to='api.demande')),
            ],
            options={
                'verbose_name': 'Intervention',
                'verbose_name_plural': 'Interventions',
            },
        ),
    ]
