# Generated by Django 6.0.5 on 2026-06-05 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiaire',
            name='nationalite',
            field=models.CharField(blank=True, default='Non spécifiée', max_length=100),
        ),
        migrations.AlterField(
            model_name='beneficiaire',
            name='situation_familiale',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiaire',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
